Table users {
    id int [pk, increment]
    name text 
    email text
    password text
    created_at timestamp
}

Table contents {
    id int [pk, increment]
    author_id int [ref: > users.id]
    title text
    description text
    body text
    created_at timestamp
    updated_at timestamp
}

Table collections {
    id int [pk, increment]
    owner_id int [ref: > users.id]
    title text
    description text
}

Table tags {
    id int [pk, increment]
    name text [unique]
}

Table content_tags {
    content_id int [ref: > contents.id]
    tag_id int [ref: > tags.id]
    indexes { (content_id, tag_id)[pk]}
}

Table collection_tags {
    collection_id int [ref: > collections.id]
    tag_id int [ref: > tags.id]
    indexes { (collection_id, tag_id)[pk]}
}

Table collection_items{
    collection_id int [ref: > collections.id]
    content_id int [ref: > contents.id]
    added_et timestamp
    indexes { (collection_id,content_id)[pk]}
}