services:
  postgres:
    image: postgres:18-alpine
    container_name: content-aggregator-db
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE}
    ports:
      - "5432:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/data
volumes: 
  postgres_data: